# Configurare Retea de baza (TCP/IPv4)
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_TCP=y
CONFIG_NET_UDP=y

# DHCP si DNS (Esentiale pentru internet)
CONFIG_NET_DHCPV4=y
CONFIG_DNS_RESOLVER=y

# Activare Wi-Fi pentru Raspberry Pi Pico W
CONFIG_WIFI=y
CONFIG_NET_L2_WIFI_MGMT=y
CONFIG_NET_MGMT_EVENT=y

# Activare Biblioteca MQTT oficiala Zephyr
CONFIG_MQTT_LIB=y

# Memorie suplimentara pentru functiile de retea
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_NET_TX_STACK_SIZE=2048
CONFIG_NET_RX_STACK_SIZE=2048

# Generare numere aleatoare (Necesar pentru securitate retea si DHCP)
CONFIG_ENTROPY_GENERATOR=y
CONFIG_TEST_RANDOM_GENERATOR=y

# Activare mesaje in Consola Seriala
CONFIG_PRINTK=y
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3








# --- CONSOLA USB ---
CONFIG_USB_DEVICE_STACK=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_UART_LINE_CTRL=y